### ISSUE TITLE
跨平台开发之Taro快速上👋

### ISSUE THREAD

**Issue by labike** [labike/labike.github.io#43]
taro.js是由京东凹凸实验室开源的跨平台框架, 在小程序当道的今天, taro.js的出现解决了React.js快速开发适配多家厂商小程序的难题, 同时为跨平台开发提供了多种选择, 即便是目前在其他平台上的兼容性处理还有欠缺, 但是它已经可以满足我们日常的业务开发需求了.

今天我们快速开发一个taro.js小程序, 废话不多说走起!

#### index.js

```javascript
import Taro, { Component } from '@tarojs/taro'
import { View, Text, Button, Image } from '@tarojs/components'
import './index.scss'

import AddQuestion from './addQuestion'
import Zan from './zan.png'
import Cai from './cai.png'

const getStorageVal = (key) => {
  if(!Taro.getStorageSync(key)){
    return []
  }
  return JSON.parse(Taro.getStorageSync(key))
}

const setStorageVal = (key, obj) => {
  let strVal = null
  if(typeof obj === 'object'){
    strVal = JSON.stringify(obj)
  }
  Taro.setStorageSync(key, strVal)
}

export default class Index extends Component {

  config = {
    navigationBarTitleText: '首页'
  }

  state = {
    showQuestionModal: false,
    questionList: getStorageVal('question')
  }

  handleClickBtn(){
    this.setState({
      showQuestionModal: true
    })
  }

  closeQuestion(){
    this.setState({
      showQuestionModal: false
    })
  }

  handleSave(opts){
    this.setState({
      questionList: [...this.state.questionList, opts]
    }, () => {
      setStorageVal('question', this.state.questionList)
    })
    this.closeQuestion()
  }

  handleAgreeIcon(item){
    let {questionList} = this.state
    if(item) item.count = item.count ? (item.count + 1) : 1
    let newList = questionList.map(newItem => {
      if(newItem.id === item.id){
        newItem = {...item}
      }
      return newItem
    })
    this.setState({
      questionList: newList
    }, () => {
      setStorageVal('question', this.state.questionList)
    })
  }
  handleDisagreeIcon(item){
    let {questionList} = this.state
    if(item) item.count = item.count ? ((item.count - 1 >= 0) ? (item.count - 1) : 0 ) : 0
    let newList = questionList.map(newItem => {
      if(newItem.id === item.id){
        newItem = {...item}
      }
      return newItem
    })
    this.setState({
      questionList: newList
    }, () => {
      setStorageVal('question', this.state.questionList)
    })
  }

  componentWillMount () { }

  componentDidMount () { }

  componentWillUnmount () { }

  componentDidShow () { }

  componentDidHide () { }

  render () {
    const {questionList} = this.state
    let newQuestionList = questionList.sort((a, b) => a.count < b.count)

    return (
      
        知乎
        
          
            {
              newQuestionList.map(item => {
                return (
                  
                    
                      
                        {item.title}
                      
                      
                        {item.desc}
                      
                    
                    
                      
                      {item.count ? item.count : 0}
                      
                    
                  
              )})
            }
          
        
        {this.state.showQuestionModal ?  : null}
        提问
      
    )
  }
}
```

#### index.scss

```scss
.index{
  margin: 0;
  padding: 0;
  .question-title{
    width: 100%;
    height: 40PX;
    line-height: 40PX;
    background: rgb(90, 88, 224);
    text-align: center;
    font-size: 20PX;
    color: #fff;
  }
  .question-btn{
    width: 100%;
    position: fixed;
    bottom: 0;
    background: rgb(131, 236, 163);
    color: #fff;
    border-radius: 0;
  }
  .question-list-content{
    .list-content{
      display: flex;
      flex-direction: column;
      .list-item{
        width: 100%;
        margin: 20PX 0;
        padding: 0 10PX;
        display: flex;
        flex-direction: row;
        justify-content: space-between;
        .item-left{
          width: 100%;
        }
        .list-title{
          font-size: 20PX;
        }
        .list-desc{
          margin-top: 5PX; 
        }
        .icon{
          width: 120PX;
          display: flex;
          flex-direction: row;
          justify-content: space-between;
          align-items: center;
          .img{
            width: 32PX;
            height: 32PX;
          }
        }
      }
    }
  }
}
```

#### Diaglog.js

```javascript
import Taro, { Component } from '@tarojs/taro'
import { View } from '@tarojs/components'

import './diaglog.scss'

class Diaglog extends Component{
  render(){
    return(
      
        {this.props.children}
      
    )
  }
}

export default Diaglog
```

#### Diaglog.scss

```scss
.diaglog{
  width: 100%;
  height: 100%;
  position: fixed;
  top: 0;
  left: 0;
  z-index: 2;
  background: #000;
}

```

#### askQuestion.js

```javascript
import Taro, { Component } from '@tarojs/taro'
import { View, Input, Textarea, Button } from '@tarojs/components'

import Diaglog from './diaglog'
import './addquestion.scss'

class AddQuestion extends Component{
  state = {
    id: parseInt(Math.random() * 1000 + new Date().getTime()),
    title: '',
    desc: ''
  }
  handleInput(e){
    this.setState({
      title: e.target.value
    })
  }
  handleTextArea(e){
    this.setState({
      desc: e.target.value
    })
  }
  handleCancle(){
    this.props.onCancle()
  }
  handleSubmit(){
    if(this.state.title && this.state.desc){
      this.props.onSave(this.state)
    }else{
      Taro.showToast({
        title: '标题或描述不能为空!',
        icon: 'none'
      })
    }
  }
  render(){
    return(
      
        
          
            
            
            
              提交
              取消
            
          
        
      
    )
  }
}

export default AddQuestion
```

#### askQuestion.scss

```scss
.add-question{
  width: 100%;
  height: 100%;
  display: flex;
  flex-direction: column;
  align-items: center;
  .question-body{
    margin-top: 100PX;
    width: 90%;
    display: flex;
    flex-direction: column;
    align-items: center;
    background: #fff;
    border-radius: 4PX;
    .question-head,
    .question-desc{
      border-bottom: 1px solid #ccc;
      margin: 10PX 0;
      padding: 10PX;
      width: 90%;
    }
    .question-desc{
      margin-bottom: 10PX;
    }
    .btn-group{
      width: 90%;
      display: flex;
      flex-direction: row;
      justify-content: space-around;
      margin-bottom: 10PX;
      .btn{
        width: 45%;
      }
      .btn-submit{
        background: #51b54d;
        color: #fff;
      }
    }
  }
}
```
![taro](https://user-images.githubusercontent.com/15871933/53946412-aecc3480-40fe-11e9-90c8-2c6dcb140adb.gif)

如果选择taro.js开发, 我觉得应该先开发小程序, 然后处理H5的兼容性问题. 另外taro.js基于React.js, 但语法上还是有些差别, 比如**父组件向子组件传递自定义点击事件, 必须以`onXXX`开头, 绑定this, 不能用箭头函数, input中不能用onChange只能用onInput等等**
